### ISSUE TITLE
Eclipse tooltip doesn't work in the Lift OML Bundle wizard

### ISSUE THREAD

**Issue by NicolasRouquette** [JPL-IMCE/gov.nasa.jpl.imce.oml.tycho#1]
See for example: [LiftOMLBundle2XcoreMetamodelWizardPage](https://github.com/JPL-IMCE/gov.nasa.jpl.imce.oml.tycho/blob/master/plugins/core/gov.nasa.jpl.imce.oml.dsl.ui/src/gov/nasa/jpl/imce/oml/dsl/ui/converter/LiftOMLBundle2XcoreMetamodelWizardPage.java#L54)

This was created using Eclipse' WindowBuilder, which in the "Design" tab allows specifying a "tooltip" on a widget (e.g., Label, Text, ...)

For example:

```java
		dsmlBundleSpecificationPath = new Text(container, SWT.BORDER);
		dsmlBundleSpecificationPath.setToolTipText("The IRI of the selected OML Bundle (read-only)");
		dsmlBundleSpecificationPath.setEnabled(false);
		dsmlBundleSpecificationPath.setEditable(false);
		dsmlBundleSpecificationPath.setText(omlBundle.iri());
```

This change seems to be ineffective: i.e., there is no tooltip that shows when the mouse is over the widget nor when pressing F2, which, according to Eclipse Spy, is the key for showing a tooltip.

It is unclear how to add Eclipse tooltips to Eclipse UIs.

**Comment by sjiherzig** [comment]
Just to throw around a few ideas:

1. There is a `setVisible(boolean visible)` method that is inherited from org.eclipse.swt.widgets.Control. Try to set visibility to true.

2. setEnabled(false) may also lead to this behavior. From the API docs: _'A disabled control is typically not selectable from the user interface and draws with an inactive or "grayed" look.'_ while this talks about color mostly, who knows what side effect it has in that context.

In Swing, the order in which these operations are called sometimes also matters. Perhaps try setting the text before calling other operations.

**Comment by NicolasRouquette** [comment]
Thanks for the comment, adding the tooltip on the label worked.
